package com.arise.jentil.embeddables;


/**
 * Autogenerated at Thu Nov 21 16:58:22 EET 2019
 */public class InfoID {
    private Long entityId;
    private Long infoId;

    public Long getEntityId() {
         return entityId;
    }
    public Long getInfoId() {
         return infoId;
    } 
    public InfoID setEntityId(Long entityId) {
          this.entityId = entityId;
          return this;
    }
    public InfoID setInfoId(Long infoId) {
          this.infoId = infoId;
          return this;
    }
}
