package com.arise.jentil.embeddables;


/**
 * Autogenerated at Thu Nov 21 16:58:22 EET 2019
 */public class Unit {
    private String code;
    private Long value;

    public Long getValue() {
         return value;
    }
    public String getCode() {
         return code;
    } 
    public Unit setValue(Long value) {
          this.value = value;
          return this;
    }
    public Unit setCode(String code) {
          this.code = code;
          return this;
    }
}
