package com.arise.core.models;

/**
 * Created by alex on 12/7/2017.
 */

public enum DialogStyle {
    OK, OK_INFO, OK_WARNING, OK_ERROR, OK_INPUT_TEXT, OK_INPUT_PASSWORD,
    OK_CANCEL, OK_CANCEL_INFO, OK_CANCEL_WARNING, OK_CANCEL_ERROR, OK_CANCEL_INPUT_TEXT, OK_CANCEL_INPUT_PASSWORD,
    YES_NO, YES_NO_INFO, YES_NO_WARNING, YES_NO_ERROR
}
