version: '2'
services:
#  sonarqube: #user admin, pass admin
#    image: sonarqube  # version - :6.7.1
#    restart: always
#    container_name: dev.arise.sonar
#    domainname: dev.arise.sonar
#    environment:
#          - SONARQUBE_JDBC_USERNAME=sonar  #same as postgres user
#          - SONARQUBE_JDBC_PASSWORD=sonar  # same as postgres pass
#          - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonarqube
#    ports:
#          - "9000:9000"
#          - "9092:9092" #elastic-search included
#
#  sonardb:
#      image: postgres
#      container_name: dev.arise.sonar.db
#      domainname: dev.arise.sonar.db
#      restart: always
#      environment:
#        - POSTGRES_USER=sonar
#        - POSTGRES_PASSWORD=sonar
#        - POSTGRES_DB=sonarqube
  #root & alex
  jenkins:
    image: jenkins/jenkins
    container_name: dev.arise.jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/alex/Dropbox/arise/docker/jenkins_volume:/var/jenkins_home

#  teamcity:
#    image: jetbrains/teamcity-server
#    container_name: dev.arise.teamcity
#    restart: always
#    ports:
#      - "8111:8111"
#    volumes:
#      - /home/alex/Dropbox/arise/docker/teamcity_volume/data:/data/teamcity_server/datadir
#      - /home/alex/Dropbox/arise/docker/teamcity_volume/logs:/opt/teamcity/logs
#      - /home/alex/Dropbox/arise/docker/teamcity_volume/webapproot:/opt/teamcity/webapps/ROOT
