package com.arise.jentil.storage.entities;

import java.util.Date;
import com.arise.jentil.embeddables.InfoID;

/**
 * Autogenerated at Thu Nov 21 16:58:22 EET 2019
 */public class FileTag {
    private Date createdOn;
    private FileEntity file;
    private InfoID id;
    private Tag tag;

    public InfoID getId() {
         return id;
    }
    public FileEntity getFile() {
         return file;
    }
    public Tag getTag() {
         return tag;
    }
    public Date getCreatedOn() {
         return createdOn;
    } 
    public FileTag setId(InfoID id) {
          this.id = id;
          return this;
    }
    public FileTag setFile(FileEntity file) {
          this.file = file;
          return this;
    }
    public FileTag setTag(Tag tag) {
          this.tag = tag;
          return this;
    }
    public FileTag setCreatedOn(Date createdOn) {
          this.createdOn = createdOn;
          return this;
    }
}
