package com.arise.jentil.storage.entities;

import java.util.Date;
import java.util.Set;

/**
 * Autogenerated at Thu Nov 21 16:58:22 EET 2019
 */public class FolderEntity {
    private Date creationDate;
    private FileEntity currentFile;
    private boolean deleted;
    private String description;
    private Long id;
    private FolderEntity parent;
    private String phase;
    private String productCode;
    private Long productId;
    private String productName;
    private String source;
    private String status;
    private Set<FolderTag> tags;
    private String type;

    public Long getId() {
         return id;
    }
    public String getStatus() {
         return status;
    }
    public Date getCreationDate() {
         return creationDate;
    }
    public FileEntity getCurrentFile() {
         return currentFile;
    }
    public boolean getDeleted() {
         return deleted;
    }
    public FolderEntity getParent() {
         return parent;
    }
    public String getType() {
         return type;
    }
    public String getDescription() {
         return description;
    }
    public String getProductName() {
         return productName;
    }
    public Long getProductId() {
         return productId;
    }
    public String getProductCode() {
         return productCode;
    }
    public String getPhase() {
         return phase;
    }
    public String getSource() {
         return source;
    }
    public Set<FolderTag> getTags() {
         return tags;
    } 
    public FolderEntity setId(Long id) {
          this.id = id;
          return this;
    }
    public FolderEntity setStatus(String status) {
          this.status = status;
          return this;
    }
    public FolderEntity setCreationDate(Date creationDate) {
          this.creationDate = creationDate;
          return this;
    }
    public FolderEntity setCurrentFile(FileEntity currentFile) {
          this.currentFile = currentFile;
          return this;
    }
    public FolderEntity setDeleted(boolean deleted) {
          this.deleted = deleted;
          return this;
    }
    public FolderEntity setParent(FolderEntity parent) {
          this.parent = parent;
          return this;
    }
    public FolderEntity setType(String type) {
          this.type = type;
          return this;
    }
    public FolderEntity setDescription(String description) {
          this.description = description;
          return this;
    }
    public FolderEntity setProductName(String productName) {
          this.productName = productName;
          return this;
    }
    public FolderEntity setProductId(Long productId) {
          this.productId = productId;
          return this;
    }
    public FolderEntity setProductCode(String productCode) {
          this.productCode = productCode;
          return this;
    }
    public FolderEntity setPhase(String phase) {
          this.phase = phase;
          return this;
    }
    public FolderEntity setSource(String source) {
          this.source = source;
          return this;
    }
    public FolderEntity setTags(Set<FolderTag> tags) {
          this.tags = tags;
          return this;
    }
}
