package com.arise.jentil.storage.entities;

import java.util.Date;
import com.arise.jentil.embeddables.InfoID;

/**
 * Autogenerated at Thu Nov 21 16:58:22 EET 2019
 */public class FolderTag {
    private Date createdOn;
    private FolderEntity folder;
    private InfoID id;
    private Tag tag;

    public InfoID getId() {
         return id;
    }
    public FolderEntity getFolder() {
         return folder;
    }
    public Tag getTag() {
         return tag;
    }
    public Date getCreatedOn() {
         return createdOn;
    } 
    public FolderTag setId(InfoID id) {
          this.id = id;
          return this;
    }
    public FolderTag setFolder(FolderEntity folder) {
          this.folder = folder;
          return this;
    }
    public FolderTag setTag(Tag tag) {
          this.tag = tag;
          return this;
    }
    public FolderTag setCreatedOn(Date createdOn) {
          this.createdOn = createdOn;
          return this;
    }
}
