package com.arise.jentil.storage.entities;


/**
 * Autogenerated at Thu Nov 21 16:58:22 EET 2019
 */public class Property {
    private Long id;
    private String key;
    private String values;

    public Long getId() {
         return id;
    }
    public String getKey() {
         return key;
    }
    public String getValues() {
         return values;
    } 
    public Property setId(Long id) {
          this.id = id;
          return this;
    }
    public Property setKey(String key) {
          this.key = key;
          return this;
    }
    public Property setValues(String values) {
          this.values = values;
          return this;
    }
}
